# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '${DATABASE_NOSQL_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_NOSQL_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_NOSQL_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_NOSQL_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_NOSQL_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DATABASE_NOSQL_USER}:${DATABASE_NOSQL_PASSWORD}@mongo:${DATABASE_NOSQL_PORT}/
