# Use root/example as user/password credentials
version: '3.1'

services:
  mysql_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_MYSQL_DATABASE}
      - MYSQL_USER=${DATABASE_MYSQL_USER}
      - MYSQL_PASSWORD=${DATABASE_MYSQL_PASSWORD}
    ports:
      - '${DATABASE_MYSQL_PORT}:3306'
